query Brands($active: Boolean!) {
  brand(where: {active: {_eq: $active}}){
    code
    id
    name
    active
    created_by {
      id
      name
    }
    updated_by{
      id
      name
    }
  }
}

mutation CreateBrand($name: String, $code: String, $user: Int) {
  insert_brand_one(object: {name: $name, code: $code, last_updated_by_id: $user, created_by_id: $user}) {
    id
  }
}

mutation EditBrand(
  $id: Int
  $name: String
  $code: String
  $user: Int
) {
  update_brand(
    where: { id: { _eq: $id } }
    _set: {
      code: $code
      name: $name
      last_updated_by_id: $user
    }
  ) {
    affected_rows
  }
}

mutation DeleteBrand($id: Int, $user: Int, $active: Boolean) {
  update_brand(
    where: { id: { _eq: $id } }
    _set: { active: $active, last_updated_by_id: $user }
  ) {
    affected_rows
  }
}
